In [107]:
import pandas as pd
import numpy as np
from functools import reduce
from itertools import combinations

In [350]:
ab = {}
ab["金"] = pd.Series({"a":5,"d":3,"r":3,"s":4,"m":4,"h":3})
ab["木"] = pd.Series({"a":3,"d":3,"r":5,"s":3,"m":4,"h":4})
ab["水"] = pd.Series({"a":2,"d":5,"r":4,"s":5,"m":3,"h":3})
ab["火"] = pd.Series({"a":4,"d":3,"r":3,"s":4,"m":5,"h":3})
ab["土"] = pd.Series({"a":2,"d":4,"r":4,"s":5,"m":2,"h":5})

In [351]:
df_ab = pd.DataFrame(ab).T

In [352]:
ke_dic = {}
ke = ["金", "木", "土", "水", "火", "金"]
for i in range(5):
    ke_dic[ke[i]+ke[i+1]] = "k"
    ke_dic[ke[i+1]+ke[i]] = "-k"
    
sheng_dic = {}
sheng = ["金", "水", "木", "火", "土", "金"]
for i in range(5):
    sheng_dic[sheng[i]+sheng[i+1]] = "s"
    sheng_dic[sheng[i+1]+sheng[i]] = "-s"

In [353]:
def rel(a,b):
    try:
        rel_ = ke_dic[a+b]
    except:
        rel_ = sheng_dic[a+b]
    if len(rel_) == 2:
        return b,a,rel_[-1]
    elif len(rel_) == 1:
        return a,b,rel_
    else:
        print("Wrong!")

In [354]:
def comp(*arg):
    m,v,r = arg[0][0],arg[0][1],arg[0][2]
    if r == "k":
        if m > v:
            return m+1
        elif m < v:
            return m-1
        else:
            return m
    elif r == "s":
        if m > v:
            return m+2
        elif m < v:
            return m
        else:
            return m+1
    else:
        print("Wrong Relationship given!")

In [355]:
def agg(a,b):
    da,db = df_ab.loc[a,],df_ab.loc[b,]
    master,vice, rel_ = rel(a,b)
    df = pd.DataFrame({master:df_ab.loc[master,], vice:df_ab.loc[vice,], "status":rel_})
    df[master+vice] = df.apply(comp, axis=1)
    return df.T.loc[master+vice,]

In [356]:
def agg_more(*arg):
    if len(arg) == 2:
        return agg(arg[0],arg[1])
    else:
        temp = pd.DataFrame({})
        for i in list(combinations(arg, len(arg)-1)):
            temp_ = agg_more(*i).astype("int64")
            temp = temp.append(temp_)
        temp = temp[list("adrsmh")]
        temp.drop_duplicates(inplace=True)
        temp.loc["".join(list(arg)),:] = temp.apply(max,axis=0)
        return temp.astype(int)

In [587]:
def bonus(*arg):
    temp = arg[0]
    bonus_ls = list(temp.name)
    level = (2 ** len(bonus_ls) - 2) ** 4
    temp += level / 2
    for i in bonus_ls:
        temp[bonus_dic[i]] += round(level,0)
        if i in ["木", "水"]:
            temp["s"] += round(level/2,0) 
        elif i in ["金", "火"]:
            temp["s"] += round(level/4,0) 
    return temp

In [575]:
def agg_more_t(*arg):
    if len(arg) == 2:
        return agg(arg[0],arg[1])
    else:
        temp = pd.DataFrame({})
        for i in list(combinations(arg, len(arg)-1)):
            temp_ = agg_more(*i).astype("int64")
            temp = temp.append(temp_)
        temp = temp[list("adrsmh")]
        temp.drop_duplicates(inplace=True)
        temp.loc["".join(list(arg)),:] = temp.apply(sum,axis=0)
        return temp.iloc[-1:,:] * len(arg)

            a        d        r       s       m        h
金木土水  11164.0  11176.0  11164.0  8464.0  1544.0  11172.0

In [588]:
final = df_ab.append(agg_more("金", "木", "土", "水", "火"))
bonus_dic = {"金":'a', "木":'r', "水":'d', "火":'m', "土":"h"}
final = final.apply(bonus,axis=1)
final["total"] = final.apply(sum,axis=1)
final = final.astype(int)
final = final.loc[sorted(final.index, key=lambda x: len(x)),:]
final

             a        d        r        s        m        h    total
金            5        3        3        4        4        3       22
木            3        3        5        3        4        4       22
水            2        5        4        5        3        3       22
火            4        3        3        4        5        3       22
土            2        4        4        5        2        5       22
金木          30       11       26       25       12       10      114
土金          26       14       14       19       10       31      114
木土          12       10       30       18       13       27      110
金水          31       27       11       24       14       12      119
水木          10       31       28       31       11       11      122
土水          10       27       12       21        9       30      109
火金          27       11       11       20       30       11      110
木火          11       12       31       23       28       14      119
火土          14       11       11       16       31       27      110
水火           9       30       13       26       26       11      115
金木土       1950      654     1950     1627      653     1951     8785
金木水       1951     1951     1948     2275      654      652     9431
金土水       1951     1950      654     1627      654     1951     8787
木土水        652     1951     1950     1951      653     1950     9107
金木火       1950      652     1951     1949     1950      654     9106
金土火       1950      654      654     1303     1951     1951     8463
木土火        654      652     1951     1624     1951     1950     8782
金水火       1951     1950      653     1950     1950      652     9106
木水火        651     1951     1951     2275     1948      654     9430
土水火        654     1950      653     1626     1951     1950     8784
金木土水     57631    57631    57630    67235    19214    57631   316972
金木土火     57630    19214    57631    57631    57631    57631   307368
金木水火     57631    57631    57631    76839    57630    19214   326576
金土水火     57631    57630    19214    57631    57631    57631   307368
木土水火     19214    57631    57631    67235    57631    57630   316972
金木土水火  1215007  1215007  1215007  1620007  1215007  1215007  7695042

In [487]:
(2 ** 2 - 2) ** 6 / 200 * 3

0.96